### ISSUE TITLE
frontend: tailwind warning

### ISSUE THREAD

**Issue by vasilyl1** [vasilyl1/team-project#109]

**Comment by vasilyl1** [comment]
![Image](https://user-images.githubusercontent.com/117856609/222746354-49742ca5-9b8d-4739-b2a5-548a4f56527e.png)

**Comment by vasilyl1** [comment]
says cdn.tailwindcss.com should not be used in production. use PostCSS plugin or use Tailwind CLI

**Comment by moonphase13** [comment]
this is normal because the tailwind cdn is still in production
